### ISSUE TITLE
Themes breaks wordpress completely if included files are not found

### ISSUE THREAD

**Issue by COLABORATI** [brettsmason/croft#3]
Please check for existing files before includes in functions.php - this breaks wordpress completely if e.g. the hybrid core files are not found. Wordpress is only spitting a 500 when included files are missing.

**Comment by brettsmason** [comment]
@COLABORATI Firstly thanks for changing the title...

Croft is a starter theme. Its meant as a starting point to build themes from and isn't ready to install and go which it sounds like you have done without first reading the instructions.

Hybrid Core is a dependancy of Croft and is used extensively throughout. If you [read the readme](https://github.com/brettsmason/croft/blob/master/README.md#getting-started-with-croft) you will see that Hybrid Core is installed for you upon running `npm install` for the first time (as well as `node_modules` and `bower_components` which are also required to develop with the theme).

I won't be adding conditionals around the includes as they are required to use the theme, and if you follow the instructions they would be present in the first place.
